### ISSUE TITLE
org.apache.solr.common.SolrException: undefined field: "event_timestamp"

### ISSUE THREAD

**Issue by phanipeddi2831** [lucidworks/banana#311] opened 2017-12-05 20:55 UTC
Hi, 
when I am trying to view data from Banana , it gives me the error 
```
org.apache.solr.common.SolrException: undefined field: "event_timestamp"
	at org.apache.solr.schema.IndexSchema.getField(IndexSchema.java:1200)
	at org.apache.solr.parser.SolrQueryParserBase.getRangeQuery(SolrQueryParserBase.java:749)
	at org.apache.solr.parser.QueryParser.Term(QueryParser.java:382)
	at org.apache.solr.parser.QueryParser.Clause(QueryParser.java:185)
	at org.apache.solr.parser.QueryParser.Query(QueryParser.java:107)
	at org.apache.solr.parser.QueryParser.TopLevelQuery(QueryParser.java:96)
	at org.apache.solr.parser.SolrQueryParserBase.parse(SolrQueryParserBase.java:151)
	at org.apache.solr.search.LuceneQParser.parse(LuceneQParser.java:50)
	at org.apache.solr.search.QParser.getQuery(QParser.java:141)
	at org.apache.solr.handler.component.QueryComponent.prepare(QueryComponent.java:193)
	at org.apache.solr.handler.component.SearchHandler.handleRequestBody(SearchHandler.java:197)
	at org.apache.solr.handler.RequestHandlerBase.handleRequest(RequestHandlerBase.java:135)
	at org.apache.solr.core.SolrCore.execute(SolrCore.java:2257)
	at org.apache.solr.servlet.SolrDispatchFilter.execute(SolrDispatchFilter.java:923)
	at org.apache.solr.servlet.SolrDispatchFilter.httpSolrCall(SolrDispatchFilter.java:484)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:260)
	at org.apache.solr.servlet.SolrDispatchFilter.doFilter(SolrDispatchFilter.java:254)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.solr.servlet.SolrHadoopAuthenticationFilter$2.doFilter(SolrHadoopAuthenticationFilter.java:408)
	at org.apache.hadoop.security.authentication.server.AuthenticationFilter.doFilter(AuthenticationFilter.java:631)
	at org.apache.hadoop.security.token.delegation.web.DelegationTokenAuthenticationFilter.doFilter(DelegationTokenAuthenticationFilter.java:301)
	at org.apache.hadoop.security.authentication.server.AuthenticationFilter.doFilter(AuthenticationFilter.java:579)
	at org.apache.solr.servlet.SolrHadoopAuthenticationFilter.doFilter(SolrHadoopAuthenticationFilter.java:413)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:233)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:103)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:293)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:859)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:610)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:503)
	at java.lang.Thread.run(Thread.java:745)
```

 . In the panel settings I dont see an option of changing the field. Moreover, I am not using that field in the bar chart and also not able to edit the query for the panel to remove that field from query. 

Is it manadatory to have event_timestamp field in all collections that I want to query from Banana dashboard. 

Please let me know

Thanks, 
Phani.

**Comment by aadel** [comment] 2017-12-05 21:25
@phanipeddi2831 it is not required to have a timestamp field for collections. If the dashboard does not include a time range query filter or a Timepicker panel, then no timestamp field is required. I guess you are working with a collection that does not have a timestamp field, so just remove the time range query filter from `Filtering` panel. Another option you can create a Non-timeseries dashboard from the `New' menu button at the top right which is designed for collections without timestamp field.

**Comment by phanipeddi2831** [comment] 2017-12-05 21:35
Thanks Aadel, creating a Non-timeseries dashboard is working fine. Thanks for prompt response.

**Comment by aadel** [comment] 2017-12-05 22:18
Cool! Closing as the issue is resolved.

**Closed as completed by aadel** 2017-12-05 22:18 UTC
